import type { RowModel } from "./types";

const MIN = 60_000;

/** One row per state from docs/PLAN.md "Sidebar rows", plus the modifiers and awkward names. */
export const FIXTURES: RowModel[] = [
  { id: "idle", name: "docs-site", project: "marketing", branch: "main", agent: "codex", status: "idle", phrase: "Idle", contextPct: 8 },
  {
    id: "working",
    name: "api-server",
    project: "my-app",
    branch: "feat/auth-flow",
    agent: "claude",
    status: "working",
    phrase: "Running npm test · 2 subagents",
    contextPct: 42,
    model: "Opus 5.5",
    effort: "high",
    subagents: 2,
    recap: { text: "Added token refresh to the auth client and is running the test suite.", ageMs: 2 * MIN },
    usage: { inContext: 84_000, window: 200_000, tokensIn: 312_000, tokensOut: 48_000, costUsd: 1.2 },
  },
  {
    id: "needs-permission",
    name: "billing",
    project: "payments",
    branch: "fix/retry-backoff",
    agent: "claude",
    status: "needs-permission",
    phrase: "Wants to run `npm test`",
    waitingMs: 65_000,
    contextPct: 61,
    flash: true,
  },
  {
    id: "needs-question",
    name: "infra",
    project: "terraform",
    branch: "chore/upgrade-aws-provider",
    agent: "gemini",
    status: "needs-question",
    phrase: "Has a question",
    waitingMs: 4 * MIN,
    contextPct: 18,
  },
  {
    id: "done-unseen",
    name: "landing",
    project: "marketing",
    branch: "feat/pricing-page",
    agent: "claude",
    status: "done-unseen",
    phrase: "Done · edited 4 files",
    ageMs: 40_000,
    contextPct: 55,
  },
  { id: "done-seen", name: "cli", project: "tools", branch: "main", agent: "codex", status: "done-seen", phrase: "Done 12m ago", ageMs: 12 * MIN, contextPct: 30 },
  {
    id: "error",
    name: "search",
    project: "my-app",
    branch: "feat/fts",
    agent: "claude",
    status: "error",
    phrase: "Stopped: rate limit reached. Resets at 3:40 pm.",
    contextPct: 97,
  },
  {
    id: "stuck",
    name: "migrations",
    project: "db",
    branch: "feat/v2-schema",
    agent: "generic",
    status: "stuck",
    phrase: "Same command 9× in 4 min",
    contextPct: 88,
  },
  { id: "ended", name: "scratch", project: "playground", agent: "generic", status: "ended", phrase: "Ended · exit 0", ageMs: 3 * 3_600_000 },
  {
    id: "limited",
    name: "legacy",
    project: "monolith",
    branch: "develop",
    agent: "codex",
    status: "limited",
    phrase: "Status limited · set up",
  },
  {
    id: "muted",
    name: "nightly-bench",
    project: "perf",
    branch: "main",
    agent: "claude",
    status: "working",
    phrase: "Running cargo bench",
    muted: true,
    contextPct: 12,
  },
  {
    id: "elevated",
    name: "drivers",
    project: "windows-setup",
    agent: "generic",
    status: "idle",
    phrase: "Administrator",
    elevated: true,
  },
  {
    id: "bypass",
    name: "refactor",
    project: "my-app",
    branch: "refactor/extract-billing-module",
    agent: "claude",
    status: "working",
    phrase: "Editing src/billing/index.ts",
    mode: "bypass",
    contextPct: 71,
  },
  {
    id: "unknown",
    name: "new-session",
    project: "my-app",
    branch: "main",
    agent: "gemini",
    status: "working",
    phrase: "Starting Gemini CLI in my-app…",
  },
  {
    id: "long-names",
    name: "a-very-long-session-name-that-will-not-fit",
    project: "an-equally-long-project-directory-name",
    branch: "feature/JIRA-12345-add-the-thing-everyone-asked-for",
    agent: "claude",
    status: "needs-permission",
    phrase: "Wants to run `rm -rf ./dist && npm run build -- --mode production`",
    waitingMs: 75 * MIN,
    contextPct: 50,
  },
  {
    id: "cjk-emoji",
    name: "認証サーバー 🚀",
    project: "프로젝트",
    branch: "fix/絵文字-🚀",
    agent: "claude",
    status: "done-unseen",
    phrase: "Done · edited 2 files",
    ageMs: 5_000,
    contextPct: 22,
  },
  {
    id: "rtl",
    name: "خادم-التحقق",
    project: "مشروع",
    branch: "main",
    agent: "codex",
    status: "idle",
    phrase: "Idle",
  },
  { id: "tiny", name: "x", project: "y", branch: "z", agent: "generic", status: "idle", phrase: "Idle" },
  {
    id: "crowded",
    name: "refactor",
    project: "my-app",
    branch: "develop",
    agent: "claude",
    status: "needs-permission",
    phrase: "Wants to run `rm -rf build`",
    mode: "bypass",
    muted: true,
    waitingMs: 59 * MIN,
    contextPct: 71,
  },
  {
    id: "emoji-name",
    name: "✅✅✅✅✅✅✅✅",
    project: "checks",
    branch: "main",
    agent: "codex",
    status: "working",
    phrase: "Running the checklist",
    contextPct: 33,
  },
  {
    id: "muted-needs-you",
    name: "nightly",
    project: "perf",
    branch: "main",
    agent: "claude",
    status: "needs-permission",
    phrase: "Wants to run `cargo bench`",
    muted: true,
    waitingMs: 3 * MIN,
    contextPct: 20,
  },
];
