pub mod api;
pub mod brand;
pub mod frames;

/// TypeScript source for the constants ts-rs cannot export (names and frame opcodes).
pub fn constants_ts() -> String {
    format!(
        "// Generated by crates/protocol (constants_ts). Do not edit.\n\
         export const APP_NAME = {app:?};\n\
         export const WS_SUBPROTOCOL = {ws:?};\n\
         export const TOKEN_SUBPROTOCOL_PREFIX = {tok:?};\n\
         export const FRAME = {{ OUTPUT: {o}, EXIT: {e}, RESET: {r}, INPUT: {i}, RESIZE: {rs}, ACK: {a}, RESUME: {re} }} as const;\n",
        app = brand::APP_NAME,
        ws = brand::WS_SUBPROTOCOL,
        tok = brand::TOKEN_SUBPROTOCOL_PREFIX,
        o = frames::OUTPUT,
        e = frames::EXIT,
        r = frames::RESET,
        i = frames::INPUT,
        rs = frames::RESIZE,
        a = frames::ACK,
        re = frames::RESUME,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn env_var_uses_prefix() {
        assert_eq!(brand::env_var("TAB_ID"), "MARSHELL_TAB_ID");
    }

    #[test]
    fn constants_ts_lists_every_opcode() {
        let ts = constants_ts();
        assert!(ts.contains("OUTPUT: 1,"));
        assert!(ts.contains("RESUME: 19 }"));
        assert!(ts.contains("export const APP_NAME = \"Marshell\";"));
    }

    /// Writes src/generated/constants.ts next to the ts-rs output.
    #[test]
    fn export_constants_ts() {
        let dir = std::env::var("TS_RS_EXPORT_DIR").expect("TS_RS_EXPORT_DIR is set in .cargo/config.toml");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(std::path::Path::new(&dir).join("constants.ts"), constants_ts()).unwrap();
    }
}
